### ISSUE TITLE
우리의 주요 타겟은 누구인가?

### ISSUE THREAD

**Issue by wesky93** [awskrug/kendra-button#10]
페르소나 기반 시나리오 만들어 보기

우리의 주요 고객이 누구일지 고민해보고 1차 가상 고객을 만들어보기(페르소나)

이후 페르소나를 바탕으로 크롤링 전략, 어드민 페이지 UX를 고민할때 참고해보면 좋을거 같습니다.

### 예시
- 일반 커뮤니티 사이트에서 자연어 검색이 필요할까?
- 동호회 사이트에서는 자연어 검색이 필요하지 않을까? ( ex. 특정 부품 살수 있는곳, 건담 색칠하는법 등)
- 스텍오버플로우 같은 사이트는 자연어 검색이 있으면 편하지 않을까?
- 서비스 제공 업체(aws,notion etc..)
    - sdk 문서 및 스택오버플로 조합데이터를 기반으로 자연어 검색 제공
- 오픈소스 프로젝트

### 결정 아이템
- [ ] 사용 할법한 고객들 전체 목록
- [ ] 1차 지원 타겟
- [ ] 1차 타겟에 대한 사용 시나리오

**Comment by hunkim** [comment]
뭔가 fact나 정보가 많은 사이트들? 정부의 정책 시책? 

사람들이 무엇을 가장 많이 질문할까요? 법령관련? 

기술 문서?
