### ISSUE TITLE
화면 설계 - 어드민 페이지

### ISSUE THREAD

**Issue by wesky93** [awskrug/kendra-button#12]
- [x] 사이트맵

- [x] 로그인 페이지

- [x] 개별 페이지

**Comment by hunkim** [comment]
로그인후 각 색인 사이트를 만들수 있어야 하고 삭제 수정 가능해야 하고

사이트에는 최소 URL, crawl/색인 주기, 본인사이트에 붙이기 위한 코드 정도가 미니멈 아닐까요? 
crawl된 문서의 수, 색인된 문서의 수, 검색관련 정보들 보여주면 될듯 하고요.

**Comment by geoseong** [comment]
금일 간단히 구상해 본 admin 페이지의 구상도입니다.
구상한 admin 페이지는 개별 페이지가 따로 없이 한 화면으로만 재사용되어 쓰일 것 같아 보입니다.

아래 그림은 [draw/screendesign.drawio.svg](./draw/screendesign.drawio.svg) 파일에서 편집 가능합니다.
![screen design](https://github.com/awskrug/kendra-button/raw/master/draw/screendesign.drawio.svg?sanitize=true)

**Comment by serithemage** [comment]
마지막의 progress bar는 그냥 처리중/완료 이 정도로만 하는게 좋지 않을까요?

**Comment by geoseong** [comment]
@wesky93 사이트맵 이랑 개별 페이지는 현 시점에서 무엇을 의미하는 걸까요? ㅎ
