### ISSUE TITLE
Amplify와 Github 리포지토리 연결 시 admin 접근권한이 필요함

### ISSUE THREAD

**Issue by geoseong** [awskrug/kendra-button#14]
현재 저희 kendra 팀원들이 해당 [kendra-button](https://github.com/awskrug/kendra-button) 깃헙 리포지토리의 admin이 아니다 보니까 Amplify 프로젝트에 Github 리포지토리 연결을 할 수가 없는 상황입니다.

![스크린샷 2020-05-26 오후 10 27 12](https://user-images.githubusercontent.com/19166187/82906613-7da88000-9fa0-11ea-828a-6c72fbd7fd92.png)

이럴 때에는 awskrug 전체 권한이 아니라 저희 kendra team에만 admin 권한 할당을 한번 해 보고 Amplify 리포지토리 설정이 잘 넘어가는 지 봐야 할 것 같습니다.

admin 권한 할당이 피요한 또다른 이유는, Github Action을 사용 할 때 secret environment 세팅을 하기 위한 권한을 얻어야 하는 이유이기도 합니다.

**Comment by wesky93** [comment]
권한 받았습니다!
