### ISSUE TITLE
Amplify Framework next.js typescript와 함께 코딩하기

### ISSUE THREAD

**Issue by geoseong** [awskrug/kendra-button#19]
### 참고문서

[~next.js examples: with-aws-amplify-typescript~](https://github.com/vercel/next.js/tree/canary/examples/with-aws-amplify-typescript)

[TypeScript Next.js example](https://github.com/vercel/next.js/tree/canary/examples/with-typescript)

**Comment by hunkim** [comment]
![image](https://user-images.githubusercontent.com/901975/83342051-75946b80-a325-11ea-8159-e6261412dda7.png)
 같은 코드 보니 code와 html이 막 섞여 있네요. 아무 재미있습니다.
