### ISSUE TITLE
크롤링 서비스 아키텍쳐 논의

### ISSUE THREAD

**Issue by wesky93** [awskrug/kendra-button#2]
## 수집 대상
- 정적 페이지
- SPA

## 사용자 요구 사항 및 해결 방안
- SPA의 경우 js실행이 되야 함
    + 셀레니움, requests-html등으로 js실행 필수
- 사용자는 url만 넣으면됨
    + 페이지에 존재 하는 모든 링크에 대해 재귀적으로 수집
    + 사용자가 설정한 도메인 이외의 링크는 무시
- 사용자가 제외 하고 싶은 페이지 설정 가능
    + 정규표현식으로 제외 경로 설정 가능 하게
- 자료수집을 위해 사용자 페이지에 추가 로직을 넣는 것을 최소화(쓰기 쉽게)
    + 버튼 클릭등으로 페이지를 넘길경우 삽입된 추적 js코드가 히스토리가 변경 될때 마다 url을 취득하여 서버로 전송하는 방안?

## 추출할 메타데이터
- host 주소
- 페이지 주소
- 

## 예상되는 수집 트리거
- 1회 수집 (변경 없는 정적 페이지)
- corn : 특정 시간에 전체 페이지를 주기적으로 재수집
- 특정 페이지 관찰 방식
    + 관찰중 추가된 링크에 대해서만 수집
        + ex
             - 사이트맵
             - 게시판 글 목록 페이지
    + 관찰 페이지 내용 변경시 전체 url에 대한 수집
        + 버전이 올라가도 문서 url이 동일한 사이트의 changelog 페이지

**Comment by hunkim** [comment]
그리고 어떤 주기로 할지도 필요해 보입니다.

**Comment by geoseong** [comment]
Frontend에서 필요한 것

- 크롤링 된 인덱스 목록 표시
- 정책 설정
