### ISSUE TITLE
Amplify API Library를 이용하여 외부 API 와 통신 시도

### ISSUE THREAD

**Issue by geoseong** [awskrug/kendra-button#20]
Amplify에서 생성하지 않은 외부 GraphQL 혹은 REST API endpoint와 통신 해 보기

## 참고문서
- GraphQL
  - [Re-use existing AppSync GraphQL API](https://docs.amplify.aws/lib/graphqlapi/create-or-re-use-existing-backend/q/platform/js#re-use-existing-appsync-graphql-api)
- REST
  - [Manual Setup: Import existing REST API](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/js#manual-setup-import-existing-rest-api)

**Comment by hunkim** [comment]
우와~ 이렇게 설정해두면 관련 API들을 접근하는 코드들도 같이 생성되나요? 

API접근을 위한 비번등도 config에 넣어두면 JS에서 보이지 않도록 하는 방법등이 있나요?

**Comment by geoseong** [comment]
@hunkim 외부 API 접근 endpoint를 config에 넣어두면 Amplify의 추상화 된 메소드를 사용하는 코딩을 직접 해야합니다 ㅎ

그리고 API접근을 위한 비번은 저희가 지금 구현할 Cognito userpool의 회원 로그인 성공 후 발행되는 token을 헤더에 실어서 보내는 방법으로 대체해야 안전할 것 같습니다

**Comment by wesky93** [comment]
아 죄송해요... ㅠㅠ cors처리를 안했네요... 잠시만요 지금 바로 봐보겠습니다

**Comment by wesky93** [comment]
@geoseong cors 처리 해서 배포했습니다.이번에도 안되면 혹시 배포한 게 있다면 확인 가능한 url 알려주시면 제가 재배포 하면서 디버깅 해보겠습니다.

**Comment by wesky93** [comment]
#25

**Comment by geoseong** [comment]
@wesky93 아 네 정상적으로 데이터 받아지는 것 확인했습니다 감사합니다 👍

**Comment by geoseong** [comment]
그리고 해당 issue는 관련 PR이 올라가서 merge될 때 닫히도록 하기 위해 남겨 두셨으면 합니다 ㅎ
