### ISSUE TITLE
로컬 개발환경 설정방법 작성

### ISSUE THREAD

**Issue by serithemage** [awskrug/kendra-button#30]
readme.md 에 로컬 개발환경 설정방법을 작성하고자 합니다.
어제 도중까지 했었는데 막히는 부분이 있어서 질문을 올립니다.
환경은 wsl2 입니다.

1. git crone 
1. amplify init
? Enter a name for the project **kendra-button**
? Enter a name for the environment **dev**
? Choose your default editor: **Visual Studio Code**
? Choose the type of app that you're building j**avascript**
Please tell us about your project
? What javascript framework are you using **react**
? Source Directory Path:  **kendra-button-front**
? Distribution Directory Path: **build**
? Build Command:  **npm run-script build**
? Start Command: **npm run-script start**

1. cd kendra-button-front
1. npm install
-> 여기서 실패합니다. 뭔가 빼먹은 기분이 드는데...
```
npm WARN saveError ENOENT: no such file or directory, open '/mnt/d/workspace/kendra-button/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/mnt/d/workspace/kendra-button/package.json'
npm WARN kendra-button No description
npm WARN kendra-button No repository field.
npm WARN kendra-button No README data
npm WARN kendra-button No license field.
```

**Comment by geoseong** [comment]
@serithemage 1번의 git clone 이후 `frontend` 폴더를 들어가서 2번의 `amplify init` 스크립트를 시작하셔야 할 것 같아요

그리고 지금 Pull Request가 Merge되면 로컬 개발환경 설정법이 조금 바뀌는데, 그건 제가 [Wiki문서: git clone 받아 frontend 프로젝트 localhost에서 실행 해 보기](https://github.com/awskrug/kendra-button/wiki/git-clone-%EB%B0%9B%EC%95%84-frontend-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-localhost%EC%97%90%EC%84%9C-%EC%8B%A4%ED%96%89-%ED%95%B4-%EB%B3%B4%EA%B8%B0)에 정리 해 놨으니 참고하시면 됩니다.

**Comment by serithemage** [comment]
감사합니다!
