### ISSUE TITLE
소셜 로그인 기능 추가

### ISSUE THREAD

**Issue by geoseong** [awskrug/kendra-button#35]
Cognito User Pool에서 연동해서 구현하기
- [x] Facebook
- [x] Google
- [ ] External Provider(Facebook, Google)의 회원정보와 UserPool의 회원정보의 attribute가 중복될 경우 하나로 합쳐주는 기능 구현
  - [x] `Userpool direct signup(native)` 추가 이후 동일 메일계정으로 `소셜로그인` 할 경우
    - [AWS-SDK: adminLinkProviderForUser](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminLinkProviderForUser-property) 을 이용하여 social provider 와 linking 시켜 userpool 정보를 update시키는 로직 구현
  - [ ] `소셜로그인` 이후 `Userpool direct signup(native)` 할 경우
    - ~[AWS-SDK: adminDisableProviderForUser](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminDisableProviderForUser-property)~
    - `PreSignUp` Cognito Lambda Trigger에서 에러를 뱉도록 구현하기

⚠️ localhost에서는 불필요하게 2번 연속으로 signUp 요청을 하는 등의 이상한 현상이 자주 일어나서 정상 작동되는 지 잘 감지하지 못했음`localhost에서 정상적인 테스트가 되지 않는 것이 가장 큰 amplify의 결함인 듯`.

**Comment by geoseong** [comment]
Error log

Google Social 로그인을 시도 했을 때...

### Step 1
try `Auth.federatedSignIn({ provider: 'Google' })`;

### Step 2
**redirected urls after logged in successfully in google login screen**

figured out `code` and `state` value changes randomly

try1: http://localhost:3000/?code=1b941e11-cf4f-4ea5-9ba3-e4ffd08e0404&state=l38KTa4vSKraK6FzG6yExUhNjKMOrGc3#

try2: http://localhost:3000/?code=7d857fa5-0a25-4e53-bd89-51ee2a7434e6&state=gu8VrR8SLOwKRAr7vl2xfqD8HrAFsH7J#

### Step 3

checked out in `Network` tab in chrome devtool

there are 2 requests to `https://{mydomain}.auth.us-west-2.amazoncognito.com/oauth2/token`

**Request 1:**

[Request URL]

    POST https://kendra-button-social-dev.auth.us-west-2.amazoncognito.com/oauth2/token

[Request Headers]

    :authority: kendra-button-social-dev.auth.us-west-2.amazoncognito.com

    :method: POST

    :path: /oauth2/token

    :scheme: https

    accept: *\/*

    accept-encoding: gzip, deflate, br

    accept-language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7

    content-length: 153

    content-type: application/x-www-form-urlencoded

    origin: http://localhost:3000

    referer: http://localhost:3000/?code=1b941e11-cf4f-4ea5-9ba3-e4ffd08e0404&state=l38KTa4vSKraK6FzG6yExUhNjKMOrGc3

    sec-fetch-dest: empty

    sec-fetch-mode: cors

    sec-fetch-site: cross-site

    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36

  [Form Data]

    grant_type: authorization_code
    code: 1b941e11-cf4f-4ea5-9ba3-e4ffd08e0404
    client_id: p252hek2d85evofb0g4u24ncg
    redirect_uri: http://localhost:3000/

  [error message]
  
    invalid_grant

**Request 2**

  [Request URL]
    same

  [Request Headers]
    same

  [Form Data]

    grant_type: authorization_code
    code: 1b941e11-cf4f-4ea5-9ba3-e4ffd08e0404
    client_id: p252hek2d85evofb0g4u24ncg
    redirect_uri: http://localhost:3000/
    code_verifier: NZypMrctZeUunENufQ3fobvqKCzsPik3I3glMTSCTLyGiKfj5Fps8aUYjC04CYXyiuV9c7GnrYBI0WFRzCqS9stvI3zyjlf6VmjfnWil3MHyGWdfdiD3AWOHCEHGBk5C

  [error message]

    invalid_request

**Comment by geoseong** [comment]
Trying to follow [Amplify Document](https://docs.amplify.aws/lib/auth/social/q/platform/js#full-react-sample)

<img width="540" alt="스크린샷 2020-06-26 오후 12 56 46" src="https://user-images.githubusercontent.com/19166187/85818848-bfe5fc80-b7ac-11ea-9caf-2f4dc6e3ebc0.png">
<img width="531" alt="스크린샷 2020-06-26 오후 12 56 37" src="https://user-images.githubusercontent.com/19166187/85818855-c4121a00-b7ac-11ea-82cb-7484225e472f.png">

**Comment by geoseong** [comment]
허나 development에서만 간헐적으로 에러가 나오며, production 에서는 에러가 나오지 않음을 확인

**Comment by chloe-codes1** [comment]
Facebook social login시 email이 등록되어 있지 않은 계정에 대해 에러가 발생함을 확인

![image](https://user-images.githubusercontent.com/53922851/85951956-4f540100-b9a1-11ea-90f5-948905bf1ac8.png)

**Comment by geoseong** [comment]
관련 이슈
- [OAuth - Error handling auth response. Error: invalid_grant](https://github.com/aws-amplify/amplify-js/issues/5829)
- [Social Login (Facebook) through user pool, hosted, ui, invalid_grant error](https://github.com/aws-amplify/amplify-js/issues/3185#issuecomment-492786930)

**Comment by geoseong** [comment]
External Provider(Facebook, Google) 구현 과정에서 PreSignUp Lambda Trigger에서 내뱉은 에러 노트

```
Invalid SourceUser: Cognito users with a username/password may not be passed in as a SourceUser, only as a DestinationUser
```

```
"PreSignUp failed with error InvalidParameterException: 1 validation error detected: Value '501e7f92-99f6-4f45-9a8d-eb521db661c9' at 'sourceUser.providerName' failed to satisfy constraint: Member must have length less than or equal to 32."
```

```
"PreSignUp failed with error AccessDeniedException:
User: arn:aws:sts::213888382832:assumed-role/kendrabuttonhosting28eb127dPreSignup-dev/kendrabuttonhosting28eb127dPreSignup-dev
is not authorized to perform: cognito-idp:AdminDisableProviderForUser on resource: *."
```

**Comment by geoseong** [comment]
link 된 유저의 email로 userpool에서 가입하려고 할 때 정상작동 후에 클라이언트에서 받는 메시지
```
code: "UsernameExistsException"
message: "An account with the given email already exists."
name: "UsernameExistsException"
```

external_provider로 가입 된 user의 email로 userpool에서 signup하려고 할 때 PreSignUp Lambda Trigger에서 막는 로직 구현 해 보기

**Comment by geoseong** [comment]
PreSignUp에서 custom error message를 뱉게 구현하는 방법
**PreSignUp Lambda Code**
```js
  ...
  return callback(JSON.stringify({
    msg: "email already exists",
  }), null);
  ...
```

**에러메시지**
```
code: "UserLambdaValidationException"
message: "PreSignUp failed with error {"msg":"email already exists"}."
name: "UserLambdaValidationException"
```

기본적으로 에러 메시지를 `PreSignUp failed with error ${Custom_Message}.` 이런 식으로 내뱉는다...
