### ISSUE TITLE
query api test case

### ISSUE THREAD

**Issue by wesky93** [awskrug/kendra-button#4]

**Comment by hunkim** [comment]
unittest 같은거 사용해서 git에 push하기 전에 테스트 되도록 할수 있나요?

**Comment by wesky93** [comment]
@hunkim  넵 테스트 작성후에는 무조건 풀리퀘스로만 푸시 하게 할까 싶습니다. 그럼 풀리퀘스트 시점에서 테스트 여부 확인 가능하고 + 코드리뷰를 하면 좋을거 같아서요

**Comment by hunkim** [comment]
cool!
