### ISSUE TITLE
SPA 페이지의 경우 어떻게 크롤링을 할지?

### ISSUE THREAD

**Issue by wesky93** [awskrug/kendra-button#6]
spa에서는 특정 행위를 하지 않으면 링크를 취득 할수 없어서 페이지 수집에 어려움이 있음. 이에 대한 아이디어 및 해결 방안 논의 필요

**Comment by wesky93** [comment]
아이디어

+ 고객 페이지에 삽입될 js sdk에서 사용자 페이지가 바뀔때 마다 base path에 포함된 경로면 kinesis firehose에 전송하기
    - 고객이 보지 않은 페이지는 크롤링이 안되서 검색 결과에 안나올 수 있음
+ 켄드라처럼 별도 API 제공(webhook 방식)
    - 사용자가 우리 서비스를 쓰기위해 백엔드에서 별도 작업을 해줘야 하기에 편하기 쓰기 어렸고 그정도 되면 굳이 우리것을 쓰는데 큰 이점이 있을지 의문 -> 추후 켄드라를 다른 인공지는 서비스로 교체하면 의미가 있음
+ 사용자에게 link가 있는 dom에 대한 정보를 받기
    - link를 찾기 위해 복잡한 행위를 해야 할경우 사용자가 그러한 프로세스를 입력하기 매우 어려움

**Comment by hunkim** [comment]
혹시 다른 웹크롤링툴에서는 어떻게 하나요?

**Comment by serithemage** [comment]
SPA 크롤링을 위한 Puppeteer라는 툴이 있네요
https://medium.com/@jasonlikenfs/a-deep-dive-guide-for-crawling-spa-with-puppeteer-and-troubleshooting-9d4bea646dd4
