### ISSUE TITLE
git 협업 스타일 결정

### ISSUE THREAD

**Issue by wesky93** [awskrug/kendra-button#8]
gitflow, github flow등 브랜치 전략 부터
브랜치, 커밋 네이밍 룰등 git과 관련된 규칙 정하고
위키에 정리하여 추후 컨트리뷰터가 늘어났을때 가이드 문서로 제공하기

## 참고
- https://ujuc.github.io/2015/12/16/git-flow-github-flow-gitlab-flow/

### 결정 아이템
- [ ] 브랜치, 커밋 네이밍 룰
- [ ]  풀리퀘, 코드리뷰, 머지 룰

**Comment by hunkim** [comment]
> https://ujuc.github.io/2015/12/16/git-flow-github-flow-gitlab-flow/ 
이 문서나 아이디어는 매우 오래된것인데 또 새로운 방식이 있을까요?

**Comment by serithemage** [comment]
git flow는 대규모 SI프로젝트에 적합합니다. 소규모나 마이크로서비스 프로젝트에서는 gitlab flow를 사용하는것이 좋고 릴리즈가 발생하지 않는 오픈소스 프로젝트에서는 github flow도 사용됩니다. 저희 프로젝트에서는 github flow나 gitlab flow가 적합해 보이네요.
