### ISSUE TITLE
Cognito UserPool 백업/복원 후 프론트엔드에서 로그인 시 "ChallengeName":"NEW_PASSWORD_REQUIRED" 응답에 대한 처리하기

### ISSUE THREAD

**Issue by chloe-codes1** [awskrug/kendra-button#80]
Cognito UserPool 의 `backup` / `restore` 는 성공하였으나, 
Restore 된 Social login user에 대한  로그인 시도 시 아래와 같은 에러를 뱉음.
```
{
"ChallengeName":"NEW_PASSWORD_REQUIRED",
"ChallengeParameters":
    {"requiredAttributes":"[]","userAttributes":" 
    {\"email_verified\":\"false\",\"email\":\"juhyun.kim@lindsey.edu\"}"},
    "Session":"...."
}
```

## TODO

- [x] `NEW_PASSWORD_REQUIRED` error에 대한 처리 필요
- [x] Backup 하려는 UserPool parameter 와 Restore 하려는 UserPool parameter 처리 필요
  - 현재는 backup 후 바로 restore하는 logic 임
  - resolved #73

**Comment by geoseong** [comment]
**Backup 하려는 UserPool parameter 와 Restore 하려는 UserPool parameter 처리 필요**

`yarn start` 스크립트에 `--mode` 플래그를 둬서 백업(backup), 복원(restore), 백업&복원(backupandrestore) 로 커맨드 입력을 통하여 실행이 되도록 구현. #73

**Comment by geoseong** [comment]
@chloe-codes1 `cognito/READEME.md` 파일명 변경 부탁드립니다 `README.md` 루요 ㅎㅎ

**Comment by geoseong** [comment]
`dev.kendra.fun`에서 구현 된 것 확인
